# Generated by Django 3.2.14 on 2022-09-04 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTKM',
            fields=[
                ('MaCT', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenCT', models.CharField(max_length=150)),
                ('NgayBatDau', models.DateTimeField()),
                ('NgayKetThuc', models.DateTimeField()),
                ('HinhThucKM', models.CharField(max_length=50)),
                ('DKADung', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CuaHang',
            fields=[
                ('MaCH', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenCH', models.CharField(max_length=150)),
                ('DiaChiCH', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='KhoNVL',
            fields=[
                ('MaNVL', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenNVL', models.CharField(max_length=50)),
                ('DvtNVL', models.CharField(max_length=10)),
                ('SoluongNVL', models.FloatField()),
                ('MaCH', models.ManyToManyField(to='api.CuaHang')),
            ],
        ),
        migrations.CreateModel(
            name='KhoSP',
            fields=[
                ('MaKSP', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenKSP', models.CharField(max_length=50)),
                ('DvtKSP', models.CharField(max_length=10)),
                ('SoluongKSP', models.FloatField()),
                ('MaCH', models.ManyToManyField(to='api.CuaHang')),
            ],
        ),
        migrations.CreateModel(
            name='KhuVuc',
            fields=[
                ('MaKV', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenKV', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('MaNV', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('HoTenNV', models.CharField(max_length=50)),
                ('DiaChiNV', models.CharField(max_length=150)),
                ('SdtNV', models.CharField(max_length=11)),
                ('ChucVu', models.CharField(max_length=30)),
                ('NgayVaoLam', models.DateTimeField()),
                ('GioiTinhNV', models.CharField(max_length=5)),
                ('NgaySinhNV', models.DateField()),
                ('EmailNV', models.EmailField(max_length=50)),
                ('MaCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cuahang')),
                ('MaKV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.khuvuc')),
            ],
        ),
        migrations.CreateModel(
            name='TheThanhVien',
            fields=[
                ('MaThe', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('HangThe', models.CharField(max_length=15)),
                ('DiemThuong', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TKNV',
            fields=[
                ('IDNVien', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Matkhau', models.CharField(max_length=15)),
                ('MaNV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='ThucUong',
            fields=[
                ('MaTU', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenTU', models.CharField(max_length=50)),
                ('DvtTU', models.CharField(max_length=10)),
                ('GiaTU', models.FloatField()),
                ('MaNVL', models.ManyToManyField(to='api.KhoNVL')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('MaSP', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenSP', models.CharField(max_length=50)),
                ('DvtSP', models.CharField(max_length=10)),
                ('GiaSP', models.FloatField()),
                ('MaKSP', models.ManyToManyField(to='api.KhoSP')),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('MaKH', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenKH', models.CharField(max_length=50)),
                ('GioiTinhKH', models.CharField(max_length=50)),
                ('NgaySinhKH', models.DateField()),
                ('EmailKH', models.EmailField(max_length=50)),
                ('DiaChiKH', models.CharField(max_length=100)),
                ('SdtKH', models.CharField(max_length=50)),
                ('Diemtichluy', models.FloatField()),
                ('Hangthanhvien', models.CharField(max_length=50)),
                ('Ngaymothe', models.DateTimeField()),
                ('MaThe', models.ManyToManyField(to='api.TheThanhVien')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('MaHD', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Ngaylaphoadon', models.DateField()),
                ('TongtientruocVAT', models.FloatField()),
                ('ThueVAT', models.FloatField()),
                ('ThanhTien', models.FloatField()),
                ('PTTToan', models.CharField(max_length=50)),
                ('MaCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cuahang')),
                ('MaCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ctkm')),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.khachhang')),
                ('MaNV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nhanvien')),
                ('MaSP', models.ManyToManyField(to='api.SanPham')),
                ('MaTU', models.ManyToManyField(to='api.ThucUong')),
            ],
        ),
        migrations.AddField(
            model_name='cuahang',
            name='MaKV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.khuvuc'),
        ),
    ]
