from django.urls import path
from . import views
from .views import (UserView,KhuVucCreate, KhuVucDestroy, KhuVucList, KhuVucUpdate, NhanVienCreate,NhanVienDestroy,
NhanVienList,NhanVienUpdate,CTKMCreate,CTKMDestroy,CTKMList,CTKMUpdate,CuaHangCreate,CuaHangDestroy,CuaHangList,
CuaHangUpdate,HoaDonCreate,SanPhamCreate,ThucUongCreate,KhachHangCreate,TheThanhVienCreate,HoaDonList,SanPhamList,
ThucUongList,KhachHangList,TheThanhVienList,HoaDonDestroy,HoaDonUpdate,SanPhamDestroy,ThucUongDestroy,KhachHangDestroy,
TheThanhVienDestroy,ThucUongUpdate,SanPhamUpdate,KhachHangUpdate,TheThanhVienUpdate,KhoNVLCreate,KhoNVLDestroy,KhoNVLList,
KhoNVLUpdate,KhoSPCreate,KhoSPDestroy,KhoSPList,KhoSPUpdate, TKNVCreate,TKNVDestroy,TKNVList,TKNVUpdate)
urlpatterns = [
    path('users', UserView.as_view()),
    path('khuvuc-list', KhuVucList.as_view()),
    path('khuvuc/<pk>/update', KhuVucUpdate.as_view()),
    path('khuvuc/<pk>/delete', KhuVucDestroy.as_view()),
    path('khuvuc-create', KhuVucCreate.as_view()),
    path('KhoNVL-list', KhoNVLList.as_view()),
    path('KhoNVL/<pk>/update', KhoNVLUpdate.as_view()),
    path('KhoNVL/<pk>/delete', KhoNVLDestroy.as_view()),
    path('KhoNVL-create', KhoNVLCreate.as_view()),
    path('KhoSP-list', KhoSPList.as_view()),
    path('KhoSP/<pk>/update', KhoSPUpdate.as_view()),
    path('KhoSP/<pk>/delete', KhoSPDestroy.as_view()),
    path('KhoSP-create', KhoSPCreate.as_view()),
    path('SanPham-list', SanPhamList.as_view()),
    path('SanPham/<pk>/update', SanPhamUpdate.as_view()),
    path('SanPham/<pk>/delete', SanPhamDestroy.as_view()),
    path('SanPham-create', SanPhamCreate.as_view()),
    path('CuaHang-list',CuaHangList.as_view()),
    path('CuaHang/<pk>/update', CuaHangUpdate.as_view()),
    path('CuaHang/<pk>/delete', CuaHangDestroy.as_view()),
    path('CuaHang-create', CuaHangCreate.as_view()),
    path('NhanVien-list',NhanVienList.as_view()),
    path('NhanVien/<pk>/update', NhanVienUpdate.as_view()),
    path('NhanVien/<pk>/delete', NhanVienDestroy.as_view()),
    path('NhanVien-create', NhanVienCreate.as_view()),
    path('TKNV-list',TKNVList.as_view()),
    path('TKNV/<pk>/update', TKNVUpdate.as_view()),
    path('TKNV/<pk>/delete', TKNVDestroy.as_view()),
    path('TKNV-create', TKNVCreate.as_view()),
    path('TheThanhVien-list',TheThanhVienList.as_view()),
    path('TheThanhVien/<pk>/update', TheThanhVienUpdate.as_view()),
    path('TheThanhVien/<pk>/delete', TheThanhVienDestroy.as_view()),
    path('TheThanhVien-create', TheThanhVienCreate.as_view()),
    path('KhachHang-list',KhachHangList.as_view()),
    path('KhachHang/<pk>/update', KhachHangUpdate.as_view()),
    path('KhachHang/<pk>/delete', KhachHangDestroy.as_view()),
    path('KhachHang-create', KhachHangCreate.as_view()),
    path('CTKM-list',CTKMList.as_view()),
    path('CTKM/<pk>/update', CTKMUpdate.as_view()),
    path('CTKM/<pk>/delete',CTKMDestroy.as_view()),
    path('CTKM-create', CTKMCreate.as_view()),
    path('HoaDon-list',HoaDonList.as_view()),
    path('HoaDon/<pk>/update', HoaDonUpdate.as_view()),
    path('HoaDon/<pk>/delete', HoaDonDestroy.as_view()),
    path('HoaDon-create', HoaDonCreate.as_view()),
    path('ThucUong-list',ThucUongList.as_view()),
    path('ThucUong/<pk>/update', ThucUongUpdate.as_view()),
    path('ThucUong/<pk>/delete', ThucUongDestroy.as_view()),
    path('ThucUong-create', ThucUongCreate.as_view()),
]